// Mocks generated by Mockito 5.3.2 from annotations
// in dart_rfb/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i4;
import 'dart:typed_data' as _i6;

import 'package:dart_rfb/src/client/config.dart' as _i3;
import 'package:dart_rfb/src/protocol/pixel_format.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRemoteFrameBufferPixelFormat_0 extends _i1.SmartFake
    implements _i2.RemoteFrameBufferPixelFormat {
  _FakeRemoteFrameBufferPixelFormat_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ConfigCopyWith_1<$Res> extends _i1.SmartFake
    implements _i3.$ConfigCopyWith<$Res> {
  _Fake$ConfigCopyWith_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternetAddress_2 extends _i1.SmartFake
    implements _i4.InternetAddress {
  _FakeInternetAddress_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRawSocketEvent_3 extends _i1.SmartFake
    implements _i4.RawSocketEvent {
  _FakeRawSocketEvent_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRawSocket_4 extends _i1.SmartFake implements _i4.RawSocket {
  _FakeRawSocket_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamSubscription_5<T> extends _i1.SmartFake
    implements _i5.StreamSubscription<T> {
  _FakeStreamSubscription_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Config].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfig extends _i1.Mock implements _i3.Config {
  MockConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get frameBufferHeight => (super.noSuchMethod(
        Invocation.getter(#frameBufferHeight),
        returnValue: 0,
      ) as int);
  @override
  int get frameBufferWidth => (super.noSuchMethod(
        Invocation.getter(#frameBufferWidth),
        returnValue: 0,
      ) as int);
  @override
  _i2.RemoteFrameBufferPixelFormat get pixelFormat => (super.noSuchMethod(
        Invocation.getter(#pixelFormat),
        returnValue: _FakeRemoteFrameBufferPixelFormat_0(
          this,
          Invocation.getter(#pixelFormat),
        ),
      ) as _i2.RemoteFrameBufferPixelFormat);
  @override
  _i3.$ConfigCopyWith<_i3.Config> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$ConfigCopyWith_1<_i3.Config>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i3.$ConfigCopyWith<_i3.Config>);
}

/// A class which mocks [RawSocket].
///
/// See the documentation for Mockito's code generation for more information.
class MockRawSocket extends _i1.Mock implements _i4.RawSocket {
  MockRawSocket() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get readEventsEnabled => (super.noSuchMethod(
        Invocation.getter(#readEventsEnabled),
        returnValue: false,
      ) as bool);
  @override
  set readEventsEnabled(bool? _readEventsEnabled) => super.noSuchMethod(
        Invocation.setter(
          #readEventsEnabled,
          _readEventsEnabled,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get writeEventsEnabled => (super.noSuchMethod(
        Invocation.getter(#writeEventsEnabled),
        returnValue: false,
      ) as bool);
  @override
  set writeEventsEnabled(bool? _writeEventsEnabled) => super.noSuchMethod(
        Invocation.setter(
          #writeEventsEnabled,
          _writeEventsEnabled,
        ),
        returnValueForMissingStub: null,
      );
  @override
  int get port => (super.noSuchMethod(
        Invocation.getter(#port),
        returnValue: 0,
      ) as int);
  @override
  int get remotePort => (super.noSuchMethod(
        Invocation.getter(#remotePort),
        returnValue: 0,
      ) as int);
  @override
  _i4.InternetAddress get address => (super.noSuchMethod(
        Invocation.getter(#address),
        returnValue: _FakeInternetAddress_2(
          this,
          Invocation.getter(#address),
        ),
      ) as _i4.InternetAddress);
  @override
  _i4.InternetAddress get remoteAddress => (super.noSuchMethod(
        Invocation.getter(#remoteAddress),
        returnValue: _FakeInternetAddress_2(
          this,
          Invocation.getter(#remoteAddress),
        ),
      ) as _i4.InternetAddress);
  @override
  bool get isBroadcast => (super.noSuchMethod(
        Invocation.getter(#isBroadcast),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<int> get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
  @override
  _i5.Future<bool> get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<_i4.RawSocketEvent> get first => (super.noSuchMethod(
        Invocation.getter(#first),
        returnValue: _i5.Future<_i4.RawSocketEvent>.value(_FakeRawSocketEvent_3(
          this,
          Invocation.getter(#first),
        )),
      ) as _i5.Future<_i4.RawSocketEvent>);
  @override
  _i5.Future<_i4.RawSocketEvent> get last => (super.noSuchMethod(
        Invocation.getter(#last),
        returnValue: _i5.Future<_i4.RawSocketEvent>.value(_FakeRawSocketEvent_3(
          this,
          Invocation.getter(#last),
        )),
      ) as _i5.Future<_i4.RawSocketEvent>);
  @override
  _i5.Future<_i4.RawSocketEvent> get single => (super.noSuchMethod(
        Invocation.getter(#single),
        returnValue: _i5.Future<_i4.RawSocketEvent>.value(_FakeRawSocketEvent_3(
          this,
          Invocation.getter(#single),
        )),
      ) as _i5.Future<_i4.RawSocketEvent>);
  @override
  int available() => (super.noSuchMethod(
        Invocation.method(
          #available,
          [],
        ),
        returnValue: 0,
      ) as int);
  @override
  int write(
    List<int>? buffer, [
    int? offset = 0,
    int? count,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            buffer,
            offset,
            count,
          ],
        ),
        returnValue: 0,
      ) as int);
  @override
  int sendMessage(
    List<_i4.SocketControlMessage>? controlMessages,
    List<int>? data, [
    int? offset = 0,
    int? count,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            controlMessages,
            data,
            offset,
            count,
          ],
        ),
        returnValue: 0,
      ) as int);
  @override
  _i5.Future<_i4.RawSocket> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<_i4.RawSocket>.value(_FakeRawSocket_4(
          this,
          Invocation.method(
            #close,
            [],
          ),
        )),
      ) as _i5.Future<_i4.RawSocket>);
  @override
  void shutdown(_i4.SocketDirection? direction) => super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [direction],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool setOption(
    _i4.SocketOption? option,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOption,
          [
            option,
            enabled,
          ],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i6.Uint8List getRawOption(_i4.RawSocketOption? option) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRawOption,
          [option],
        ),
        returnValue: _i6.Uint8List(0),
      ) as _i6.Uint8List);
  @override
  void setRawOption(_i4.RawSocketOption? option) => super.noSuchMethod(
        Invocation.method(
          #setRawOption,
          [option],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Stream<_i4.RawSocketEvent> asBroadcastStream({
    void Function(_i5.StreamSubscription<_i4.RawSocketEvent>)? onListen,
    void Function(_i5.StreamSubscription<_i4.RawSocketEvent>)? onCancel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #asBroadcastStream,
          [],
          {
            #onListen: onListen,
            #onCancel: onCancel,
          },
        ),
        returnValue: _i5.Stream<_i4.RawSocketEvent>.empty(),
      ) as _i5.Stream<_i4.RawSocketEvent>);
  @override
  _i5.StreamSubscription<_i4.RawSocketEvent> listen(
    void Function(_i4.RawSocketEvent)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [onData],
          {
            #onError: onError,
            #onDone: onDone,
            #cancelOnError: cancelOnError,
          },
        ),
        returnValue: _FakeStreamSubscription_5<_i4.RawSocketEvent>(
          this,
          Invocation.method(
            #listen,
            [onData],
            {
              #onError: onError,
              #onDone: onDone,
              #cancelOnError: cancelOnError,
            },
          ),
        ),
      ) as _i5.StreamSubscription<_i4.RawSocketEvent>);
  @override
  _i5.Stream<_i4.RawSocketEvent> where(
          bool Function(_i4.RawSocketEvent)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [test],
        ),
        returnValue: _i5.Stream<_i4.RawSocketEvent>.empty(),
      ) as _i5.Stream<_i4.RawSocketEvent>);
  @override
  _i5.Stream<S> map<S>(S Function(_i4.RawSocketEvent)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #map,
          [convert],
        ),
        returnValue: _i5.Stream<S>.empty(),
      ) as _i5.Stream<S>);
  @override
  _i5.Stream<E> asyncMap<E>(
          _i5.FutureOr<E> Function(_i4.RawSocketEvent)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #asyncMap,
          [convert],
        ),
        returnValue: _i5.Stream<E>.empty(),
      ) as _i5.Stream<E>);
  @override
  _i5.Stream<E> asyncExpand<E>(
          _i5.Stream<E>? Function(_i4.RawSocketEvent)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #asyncExpand,
          [convert],
        ),
        returnValue: _i5.Stream<E>.empty(),
      ) as _i5.Stream<E>);
  @override
  _i5.Stream<_i4.RawSocketEvent> handleError(
    Function? onError, {
    bool Function(dynamic)? test,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleError,
          [onError],
          {#test: test},
        ),
        returnValue: _i5.Stream<_i4.RawSocketEvent>.empty(),
      ) as _i5.Stream<_i4.RawSocketEvent>);
  @override
  _i5.Stream<S> expand<S>(Iterable<S> Function(_i4.RawSocketEvent)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #expand,
          [convert],
        ),
        returnValue: _i5.Stream<S>.empty(),
      ) as _i5.Stream<S>);
  @override
  _i5.Future<dynamic> pipe(
          _i5.StreamConsumer<_i4.RawSocketEvent>? streamConsumer) =>
      (super.noSuchMethod(
        Invocation.method(
          #pipe,
          [streamConsumer],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Stream<S> transform<S>(
          _i5.StreamTransformer<_i4.RawSocketEvent, S>? streamTransformer) =>
      (super.noSuchMethod(
        Invocation.method(
          #transform,
          [streamTransformer],
        ),
        returnValue: _i5.Stream<S>.empty(),
      ) as _i5.Stream<S>);
  @override
  _i5.Future<_i4.RawSocketEvent> reduce(
          _i4.RawSocketEvent Function(
    _i4.RawSocketEvent,
    _i4.RawSocketEvent,
  )?
              combine) =>
      (super.noSuchMethod(
        Invocation.method(
          #reduce,
          [combine],
        ),
        returnValue: _i5.Future<_i4.RawSocketEvent>.value(_FakeRawSocketEvent_3(
          this,
          Invocation.method(
            #reduce,
            [combine],
          ),
        )),
      ) as _i5.Future<_i4.RawSocketEvent>);
  @override
  _i5.Future<S> fold<S>(
    S? initialValue,
    S Function(
      S,
      _i4.RawSocketEvent,
    )?
        combine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fold,
          [
            initialValue,
            combine,
          ],
        ),
        returnValue: _i5.Future<S>.value(null),
      ) as _i5.Future<S>);
  @override
  _i5.Future<String> join([String? separator = r'']) => (super.noSuchMethod(
        Invocation.method(
          #join,
          [separator],
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<bool> contains(Object? needle) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [needle],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<dynamic> forEach(void Function(_i4.RawSocketEvent)? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #forEach,
          [action],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<bool> every(bool Function(_i4.RawSocketEvent)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #every,
          [test],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<bool> any(bool Function(_i4.RawSocketEvent)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #any,
          [test],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Stream<R> cast<R>() => (super.noSuchMethod(
        Invocation.method(
          #cast,
          [],
        ),
        returnValue: _i5.Stream<R>.empty(),
      ) as _i5.Stream<R>);
  @override
  _i5.Future<List<_i4.RawSocketEvent>> toList() => (super.noSuchMethod(
        Invocation.method(
          #toList,
          [],
        ),
        returnValue:
            _i5.Future<List<_i4.RawSocketEvent>>.value(<_i4.RawSocketEvent>[]),
      ) as _i5.Future<List<_i4.RawSocketEvent>>);
  @override
  _i5.Future<Set<_i4.RawSocketEvent>> toSet() => (super.noSuchMethod(
        Invocation.method(
          #toSet,
          [],
        ),
        returnValue:
            _i5.Future<Set<_i4.RawSocketEvent>>.value(<_i4.RawSocketEvent>{}),
      ) as _i5.Future<Set<_i4.RawSocketEvent>>);
  @override
  _i5.Future<E> drain<E>([E? futureValue]) => (super.noSuchMethod(
        Invocation.method(
          #drain,
          [futureValue],
        ),
        returnValue: _i5.Future<E>.value(null),
      ) as _i5.Future<E>);
  @override
  _i5.Stream<_i4.RawSocketEvent> take(int? count) => (super.noSuchMethod(
        Invocation.method(
          #take,
          [count],
        ),
        returnValue: _i5.Stream<_i4.RawSocketEvent>.empty(),
      ) as _i5.Stream<_i4.RawSocketEvent>);
  @override
  _i5.Stream<_i4.RawSocketEvent> takeWhile(
          bool Function(_i4.RawSocketEvent)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #takeWhile,
          [test],
        ),
        returnValue: _i5.Stream<_i4.RawSocketEvent>.empty(),
      ) as _i5.Stream<_i4.RawSocketEvent>);
  @override
  _i5.Stream<_i4.RawSocketEvent> skip(int? count) => (super.noSuchMethod(
        Invocation.method(
          #skip,
          [count],
        ),
        returnValue: _i5.Stream<_i4.RawSocketEvent>.empty(),
      ) as _i5.Stream<_i4.RawSocketEvent>);
  @override
  _i5.Stream<_i4.RawSocketEvent> skipWhile(
          bool Function(_i4.RawSocketEvent)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipWhile,
          [test],
        ),
        returnValue: _i5.Stream<_i4.RawSocketEvent>.empty(),
      ) as _i5.Stream<_i4.RawSocketEvent>);
  @override
  _i5.Stream<_i4.RawSocketEvent> distinct(
          [bool Function(
            _i4.RawSocketEvent,
            _i4.RawSocketEvent,
          )?
              equals]) =>
      (super.noSuchMethod(
        Invocation.method(
          #distinct,
          [equals],
        ),
        returnValue: _i5.Stream<_i4.RawSocketEvent>.empty(),
      ) as _i5.Stream<_i4.RawSocketEvent>);
  @override
  _i5.Future<_i4.RawSocketEvent> firstWhere(
    bool Function(_i4.RawSocketEvent)? test, {
    _i4.RawSocketEvent Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #firstWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i5.Future<_i4.RawSocketEvent>.value(_FakeRawSocketEvent_3(
          this,
          Invocation.method(
            #firstWhere,
            [test],
            {#orElse: orElse},
          ),
        )),
      ) as _i5.Future<_i4.RawSocketEvent>);
  @override
  _i5.Future<_i4.RawSocketEvent> lastWhere(
    bool Function(_i4.RawSocketEvent)? test, {
    _i4.RawSocketEvent Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i5.Future<_i4.RawSocketEvent>.value(_FakeRawSocketEvent_3(
          this,
          Invocation.method(
            #lastWhere,
            [test],
            {#orElse: orElse},
          ),
        )),
      ) as _i5.Future<_i4.RawSocketEvent>);
  @override
  _i5.Future<_i4.RawSocketEvent> singleWhere(
    bool Function(_i4.RawSocketEvent)? test, {
    _i4.RawSocketEvent Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #singleWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i5.Future<_i4.RawSocketEvent>.value(_FakeRawSocketEvent_3(
          this,
          Invocation.method(
            #singleWhere,
            [test],
            {#orElse: orElse},
          ),
        )),
      ) as _i5.Future<_i4.RawSocketEvent>);
  @override
  _i5.Future<_i4.RawSocketEvent> elementAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #elementAt,
          [index],
        ),
        returnValue: _i5.Future<_i4.RawSocketEvent>.value(_FakeRawSocketEvent_3(
          this,
          Invocation.method(
            #elementAt,
            [index],
          ),
        )),
      ) as _i5.Future<_i4.RawSocketEvent>);
  @override
  _i5.Stream<_i4.RawSocketEvent> timeout(
    Duration? timeLimit, {
    void Function(_i5.EventSink<_i4.RawSocketEvent>)? onTimeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #timeout,
          [timeLimit],
          {#onTimeout: onTimeout},
        ),
        returnValue: _i5.Stream<_i4.RawSocketEvent>.empty(),
      ) as _i5.Stream<_i4.RawSocketEvent>);
}
