name: dart_rfb
description: Implementation of The Remote Framebuffer Protocol (RFC 6143, aka VNC protocol)
version: 0.0.2
repository: https://github.com/Goddchen/dart-rfb

environment:
  sdk: ">=2.18.4 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  fake_async: ^1.3.1
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.16.0
dependencies:
  collection: ^1.16.0
  fpdart: ^0.4.0
  freezed_annotation: ^2.2.0
  logging: ^1.1.0
