name: main workflow
on:
  push:
    branches:
      - main
jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 3.1.0
      - run: dart pub get
      - run: dart analyze --fatal-infos --fatal-warnings
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 3.1.0
      - run: dart format --output none --set-exit-if-changed .\example\ .\lib\ .\test\
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 3.1.0
      - run: dart test
