name: publish workflow
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
      - name: Setup credentials
        env:
          PUB_DEV_CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
        run: |
          mkdir -p ~/.config/dart
          echo $PUB_DEV_CREDENTIALS > ~/.config/dart/pub-credentials.json
      - run: dart pub publish -f
